/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myapplication_JNITools */

#ifndef _Included_com_example_myapplication_JNITools
#define _Included_com_example_myapplication_JNITools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_myapplication_JNITools
 * Method:    addNum
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_myapplication_JNITools_addNum
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     com_example_myapplication_JNITools
 * Method:    caLLJavaMehodFormJni
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_myapplication_JNITools_caLLJavaMehodFormJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
